[tools]
go = "latest"
usage = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
pipx.uvx = true

[plugins]
nix = "https://github.com/mise-plugins/mise-nix"

[hooks]
enter = "mise i -q"

